# Generated by Django 4.2.11 on 2024-11-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_API', '0002_remove_employee_position_remove_employee_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('group_id', models.IntegerField(max_length=5, unique=True)),
            ],
        ),
    ]
