# Generated by Django 4.2.11 on 2024-11-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_API', '0003_employeegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_nr',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
