# Generated by Django 4.2.11 on 2024-11-17 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding_API', '0004_alter_employee_experience_alter_employee_phone_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_group',
            field=models.CharField(choices=[], default='RK', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
