# Generated by Django 4.2.11 on 2024-11-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_API', '0005_alter_employee_employee_group_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeegroup',
            name='group_id',
            field=models.IntegerField(unique=True),
        ),
    ]
