# Generated by Django 4.2.11 on 2024-11-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_API', '0006_alter_employeegroup_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_group',
            field=models.CharField(choices=[], default='1', max_length=20),
        ),
    ]
