# Generated by Django 4.2.11 on 2024-11-17 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_API', '0007_alter_employee_employee_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onboarding_API.employeegroup'),
        ),
    ]
