# Generated by Django 4.2.11 on 2024-11-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding_API', '0011_rank_skilllevel_tool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='skill_level',
        ),
        migrations.DeleteModel(
            name='SkillLevel',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
